# `numpy`
- Multidimensional array library 



### *why we use numpy over lists?*
- the main difference comes from the speed so the lists are very slow meanwhile numpy is very fast 

- In lists i can not do element-wise maths operations as i do in numpy 
```python
    lists : 
    a = [1 , 3 , 5]
    b = [1 , 2 , 4]
    a *b = error 
```
```python
    Numpy: 
    a = np.array([1 , 3 , 5])
    b = np.array([1 , 2 , 6])
    a*b = np.array([1 , 6 , 30])

```
##### *Why numpy is faster?*
- numpy use `fixed types` and lists use `bulit_in type` for python 
- `fixed types` Faster to read less bytes of memory and no type checking when iterating through objects 
- Numpy utilizes contiguous memory (objects in memory next to each other)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 3, 6])
print(a)

[1 3 6]


In [3]:
b = np.array([[1, 3, 5], [2, 5, 6]], dtype="float")
print(b)

[[1. 3. 5.]
 [2. 5. 6.]]


In [4]:
# Get the dimension of the arrays
b.ndim

2

In [5]:
# Get the shape
b.shape

(2, 3)

In [6]:
# Get the type
b.dtype

dtype('float64')

In [7]:
# Get the item size
# int32 = 4 byte
# int16 = 2 byte
# float64 = 8 byte
# floats are bigger than integers
b.itemsize

8

In [8]:
# Get the total size
b.size * b.itemsize

48

In [9]:
# Get the total size
b.nbytes

48

#### Accessing/Changing Specific elements rows , columns 

In [10]:
a = np.array([[1, 2, 4, 5, 6, 12], [1, 4, 6, 7, 10, 22]])
print(a)

[[ 1  2  4  5  6 12]
 [ 1  4  6  7 10 22]]


In [11]:
# Get a specific item [row , col]

a[1, 4]
a[1, -2]

10

In [12]:
# Get a specific row
a[0, :]

array([ 1,  2,  4,  5,  6, 12])

In [13]:
# Get s specific colum
a[:, 5]

array([12, 22])

In [14]:
# Getting a little fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([ 2,  5, 12])

In [15]:
a[1, 5] = 32
a

array([[ 1,  2,  4,  5,  6, 12],
       [ 1,  4,  6,  7, 10, 32]])

In [16]:
a[:, 2] = 6, 2
a

array([[ 1,  2,  6,  5,  6, 12],
       [ 1,  4,  2,  7, 10, 32]])

3-d example 

In [17]:
b = np.array([[[1, 3], [2, 5]], [[4, 6], [8, 10]]])
print(b)

[[[ 1  3]
  [ 2  5]]

 [[ 4  6]
  [ 8 10]]]


In [18]:
b.ndim

3

In [19]:
b[0, 1, 1]

5

In [20]:
b[:, 1, :]

array([[ 2,  5],
       [ 8, 10]])

In [21]:
b[:, 1, :]  # arr , row , col

array([[ 2,  5],
       [ 8, 10]])

In [22]:
# Changing items

print("before\n")
print(b)

b[:, 0, :] = [[8, 8], [9, 9]]

print("after\n")
print(b)

before

[[[ 1  3]
  [ 2  5]]

 [[ 4  6]
  [ 8 10]]]
after

[[[ 8  8]
  [ 2  5]]

 [[ 9  9]
  [ 8 10]]]


### Initializing different types of arrays 

In [23]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((5, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [25]:
np.full((2, 2), fill_value=55, dtype="float")

array([[55., 55.],
       [55., 55.]])

In [26]:
a

array([[ 1,  2,  6,  5,  6, 12],
       [ 1,  4,  2,  7, 10, 32]])

In [27]:
# any other
np.full_like(a, fill_value=5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [28]:
# random
np.random.rand(3, 4, 2)  # arr , row , col

array([[[0.63328873, 0.03662843],
        [0.61011788, 0.14232458],
        [0.59366855, 0.08062322],
        [0.73720128, 0.62991074]],

       [[0.16109688, 0.65565629],
        [0.94847275, 0.86671119],
        [0.79575447, 0.97092258],
        [0.13959281, 0.57906989]],

       [[0.99461258, 0.86440551],
        [0.25582808, 0.68493494],
        [0.64739667, 0.98619632],
        [0.87647785, 0.17262959]]])

In [29]:
# random decimal values
np.random.random_sample(a.shape)

array([[0.03239023, 0.97695653, 0.90546935, 0.09226692, 0.71107277,
        0.296914  ],
       [0.35573083, 0.47431427, 0.06411013, 0.99625436, 0.905225  ,
        0.15568088]])

In [39]:
# random integer values
np.random.randint(-1, 5, size=(3, 3))

array([[ 0,  4,  4],
       [ 0,  4, -1],
       [-1,  4,  2]])

In [40]:
# identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Repeat an array
a = np.array([[1, 2, 3]])
arr = np.repeat(a, 3, axis=0)
print(arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [45]:
print(arr.shape)

(3, 3)


In [51]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
print(z)
z[1, 1] = 9
print(z)

# now concatnate z in out
output[1:4, 1:4] = z.copy()
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful with copy

In [53]:
a = np.array([1, 3, 5])
b = a
b[1] = 100
print(b)
print(a)

[  1 100   5]
[  1 100   5]


In [55]:
a = np.array([1, 3, 5])
b = a.copy()
b[1] = 100
print(b)
print(a)

[  1 100   5]
[1 3 5]


#### Mathematics Operations 

In [57]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [58]:
a += 2
a

array([3, 4, 5, 6])

In [59]:
a * 2

array([ 6,  8, 10, 12])

In [60]:
b = np.array([1, 2, 3, 4])
print(a)
print(b)

[3 4 5 6]
[1 2 3 4]


In [62]:
a * b

array([ 3,  8, 15, 24])

### some important operations in numpy

In [63]:
a = np.array([4.0, 2.0])
b = np.array([3.0, 8.0])

np.vstack([a, b])

array([[4., 2.],
       [3., 8.]])

In [65]:
np.hstack([a, b])

array([4., 2., 3., 8.])

In [68]:
# matrix multiplaction
x = np.array([1, 2, 3])
y = np.array([3, 2, 10])

x.dot(y)

37

#### Broadcasting 

In [69]:
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([1, 2, 3])

a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [71]:
np.ones(3) + np.ones(3)

array([2., 2., 2.])

In [75]:
a = np.ones((3, 1)) + np.ones(3)
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [76]:
a.shape

(3, 3)